reunion/config/routes.rb
Reunion::Application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :reunion_options do
      get :who_bought, :on => :member
    end
    root :to => 'reunion_store#index', :as => 'reunion_store'
  end
end
 


  

reunion/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Class of 1967 45th Reunion: Registration and Store</title>
<!-- START:stylesheet -->
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "reunion", :media => "all" %>
  <!-- the reunion.css stylesheet provides reunion page style commands  -->
<!-- <label id="code.slt"/> -->
<!-- END:stylesheet -->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <!-- <label id="code.csrf"/> -->
  <!-- the label id sets up behind the scenes data needed to prevent  -->
  <!-- cross-site scripting requests -->
</head>
<body id="reunion_store">
  <div id="banner">
    <%= image_tag("Crest1967_small.jpg") %>
    <%= @page_title || "Reunion Registration and Store" %><!-- <label id="code.reunion.e.title"/> -->
  </div>
  <div id="columns">
    <div id="side">
    	<!-- START_HIGHLIGHT -->
        <!-- START:hidden_div -->
        <!-- START_HIGHLIGHT -->
        <% if @cart %>
        <!-- END_HIGHLIGHT -->
            <%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
               <%= render @cart %>
            <% end %>
        <!-- START_HIGHLIGHT -->
        <% end %>
        <!-- END_HIGHLIGHT -->
        <!-- END:hidden_div -->
      <!-- END_HIGHLIGHT -->
      <%= link_to 'Reunion Registration and Store',   ''   %><br />
      <a href="http://www.west-point.org/class/usma1967/Reunion2012.html">Reunion Overview</a><br />
      <a href="http://www.west-point.org/class/usma1967/Reunion 2012/Schedule of Events.pdf">Reunion Schedule</a><br />
      <a href="http://www.west-point.org/class/usma1967/Reunion 2012/Class_of_1967_45th_Reunion_Golf_Outing.pdf">Reunion Golf Outing</a><br />
      <a href="http://www.west-point.org/class/usma1967/Reunion 2012/Class_of_1967_45th_Reunion_Tours.pdf">Reunion Tours</a><br />

      <% if session[:user_id] %>
        <br />
        <%= link_to 'Orders',   orders_path   %><br />
        <%= link_to 'Reunion Options', reunion_options_path %><br />
        <%= link_to 'Users',    users_path    %><br />
        <br />
        <%= button_to 'Logout', logout_path, :method => :delete   %>
      <% end %>
    </div>
    <div id="main">
      <%= yield %>  
    </div>
  </div>
</body>
</html>